### ISSUE TITLE
versions of packages in mlde.yml

### ISSUE THREAD

**Issue by xrz14** [fhalab/MLDE#9]
The specified versions of packages in mlde.yml are quite outdated, making them unavailable. Additionally, newer versions of these packages may offer improved performance. It might be advisable to update the versions of these packages.

**Comment by brucejwittmann** [comment]
Hi! The versions provided in the mlde.yml file are to enable reproduction of the experiments in the associated paper. You can certainly use other versions if you wish. I'd recommend running the unit tests with new versions to make sure that everything works as expected.
